[package]
name = "mawawdi/gun-system"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Knit = "sleitnick/knit@^1.7"
Promise = "evaera/promise@4.0.0"
Maid = "devsparkle/maid@2.1.0"
FastCastRedux = "megamonsta2/fastcastredux@13.2.7"
Fusion = "elttob/fusion@0.3.0"
